name: Docker Base Image CI

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version to build this image with.'
        type: choice
        required: true
        default: '16'
        options:
          - '16'
          - '18'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./docker/images/n8n-base
          build-args: |
            NODE_VERSION=${{github.event.inputs.node_version}}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          provenance: false
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/base:${{ github.event.inputs.node_version }}
