name: 'Release: Push to Channel'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'n8n Release version to push to a channel'
        required: true

      release-channel:
        description: 'Release channel'
        required: true
        type: choice
        default: 'next'
        options:
          - next
          - latest

jobs:
  release-to-docker-hub:
    name: Release to DockerHub
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/n8n:${{ github.event.inputs.release-channel }} ghcr.io/${{ github.repository_owner }}/n8n:${{ github.event.inputs.version }}
